singleQuote: true
semi: false
printWidth: 100
trailingComma: none
tabWidth: 4
overrides:
  - files: '*.{yaml,yml,json,md,config.js}'
    options:
      tabWidth: 2
  - files: ['docker-compose.{yml,yaml}', 'compose.{yml,yaml}']
    options:
      tabWidth: 4
      singleQuote: false
plugins: ['prettier-plugin-tailwindcss']
