services:
    sqlserver:
        build: ./database
        container_name: sqlserver2019
        ports:
            - "${MSSQL_PORT}:1433"
        environment:
            ACCEPT_EULA: ${ACCEPT_EULA}
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
            MSSQL_PID: ${MSSQL_PID}
        volumes:
            - sqlserver_data:/var/opt/mssql
        restart: unless-stopped

    frontend:
        build: ./frontend
        container_name: synapse-frontend
        ports:
            - "3000:80"
        restart: unless-stopped

    backend:
        build: ./backend
        container_name: synapse-backend
        env_file:
            - ./backend/.env.docker
        restart: unless-stopped

    ai:
        build: ./ai
        container_name: synapse-ai
        env_file:
            - ./ai/.env.docker
        restart: unless-stopped

volumes:
    sqlserver_data:
