version: "3.9"

services:
    sqlserver:
        build: ./database
        container_name: sqlserver2019
        ports:
            - "${MSSQL_PORT}:1433"
        environment:
            ACCEPT_EULA: ${ACCEPT_EULA}
            MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
            MSSQL_PID: ${MSSQL_PID}
        volumes:
            - sqlserver_data:/var/opt/mssql
        restart: unless-stopped

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: synapse-frontend
        ports:
            - "3000:5173"
        volumes:
            - ./frontend:/app
            - /app/node_modules
        restart: unless-stopped
volumes:
    sqlserver_data:
