flowchart LR
    %% Components

        FE[Frontend]
        BE[Backend]
        AI[AI Service]
        DB[Database]

    %% Interactions
    FE -- "HTTP requests" --> BE
    BE -- "API/AI responses" --> FE
    BE -- "User/AI queries" --> DB
    DB -- "Query results" --> BE
    BE -- "AI requests/Data" --> AI
    AI -- "Responses / DB queries" --> BE